import { Recipe } from '../types/recipe';

export const INITIAL_DEMO_RECIPES: Recipe[] = [
  {
    id: 'demo-gramigna',
    user_id: 'chef-martina-russo',
    author: {
      id: 'chef-martina-russo',
      username: 'martina_russo',
      full_name: 'Martina Russo',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      bio: 'Food creator & pasta enthusiast. Amo i primi piatti veloci, cremosi e conviviali.',
      is_private: false,
    },
    title: 'Gramigna alla Salsiccia',
    category: 'Primi',
    prep_time: '20 min',
    servings: 2,
    calories: 1320,
    created_at: new Date().toISOString(),
    source_url: 'https://www.instagram.com/reel/martinarusso_real/',
    source_type: 'instagram',
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3d5d62817d3?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { id: 'ing-g1', name: 'Gramigna', amount: '250 g' },
      { id: 'ing-g2', name: 'Salsicce', amount: '2 salsicce' },
      { id: 'ing-g3', name: 'Panna da cucina', amount: '200 g' },
      { id: 'ing-g4', name: 'Concentrato di pomodoro', amount: '1 cucchiaino' },
      { id: 'ing-g5', name: 'Burro', amount: '1 noce' },
      { id: 'ing-g6', name: 'Parmigiano Reggiano grattugiato', amount: '30 g' },
      { id: 'ing-g7', name: 'Pepe nero macinato', amount: 'q.b.' },
      { id: 'ing-g8', name: 'Sale fino', amount: 'q.b.' },
    ],
    steps: [
      { id: 'step-g1', step: 1, instruction: 'Togli il budello alle due salsicce e sgranale finemente a tocchetti con le dita o con una forchetta.' },
      { id: 'step-g2', step: 2, instruction: 'In una padella antiaderente capiente fai sciogliere una generosa noce di burro a fiamma vivace.' },
      { id: 'step-g3', step: 3, instruction: 'Unisci la salsiccia sgranata e falla rosolare per circa 5-7 minuti mescolando spesso, finché non risulterà ben dorata, croccante e sfrigolante. Se gradito, aggiungi abbondante pepe nero.' },
      { id: 'step-g4', step: 4, instruction: 'Aggiungi un cucchiaino di concentrato di pomodoro e lascialo tostare per un minuto a contatto con il fondo caldo per sprigionare tutto il suo aroma.' },
      { id: 'step-g5', step: 5, instruction: 'Versa 200 g di panna da cucina direttamente in padella, abbassa la fiamma e mescola per 2-3 minuti fino a ottenere un sugo cremoso, vellutato e dal caratteristico colore rosato.' },
      { id: 'step-g6', step: 6, instruction: 'Cuoci la gramigna in abbondante acqua bollente salata e scolala bene al dente.' },
      { id: 'step-g7', step: 7, instruction: 'Tuffa la gramigna nella padella con la crema di salsiccia e panna, unisci abbondante Parmigiano Reggiano grattugiato e salta a fuoco vivo per mantecare il tutto alla perfezione. Servi calda!' },
    ],
  },
  {
    id: 'demo-1',
    user_id: 'chef-marco-bianchi',
    author: {
      id: 'chef-marco-bianchi',
      username: 'chef_marco',
      full_name: 'Marco Bianchi',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      bio: 'Chef toscano appassionato di antipasti rustici e ingredienti a km 0.',
      is_private: false,
    },
    title: 'Bruschette Rustiche al Pomodoro e Basilico',
    category: 'Antipasti',
    prep_time: '15 min',
    servings: 4,
    calories: 920,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { id: 'ing-1', name: 'Pane casereccio o di Altamura a fette', amount: '8 fette' },
      { id: 'ing-2', name: 'Pomodori ramati o datterini maturi', amount: '400g' },
      { id: 'ing-3', name: 'Foglie di basilico fresco', amount: '1 mazzetto' },
      { id: 'ing-4', name: 'Spicchi d\'aglio fresco', amount: '2 spicchi' },
      { id: 'ing-5', name: 'Olio extravergine d\'oliva fruttato', amount: '4 cucchiai' },
      { id: 'ing-6', name: 'Origano essiccato e sale a scaglie', amount: 'q.b.' },
    ],
    steps: [
      { id: 'step-1', step: 1, instruction: 'Lava con cura i pomodori, rimuovi i semi in eccesso e tagliali a cubetti regolari di circa mezzo centimetro.' },
      { id: 'step-2', step: 2, instruction: 'Trasferisci i pomodori in una ciotola capiente, condiscili con olio EVO generoso, foglie di basilico spezzettate a mano, sale e un pizzico di origano. Mescola e lascia marinare per 10 minuti affinché i sapori si fondano.' },
      { id: 'step-3', step: 3, instruction: 'Tosta le fette di pane casereccio su una piastra rovente o in forno a 200°C fino a ottenere una doratura croccante all\'esterno ma soffice all\'interno.' },
      { id: 'step-4', step: 4, instruction: 'Sfrega delicatamente uno spicchio d\'aglio spellato sulla superficie calda di ogni fetta di pane bruschettata.' },
      { id: 'step-5', step: 5, instruction: 'Distribuisci la concassé di pomodori marinati sulle fette, irrora con il liquido aromatico rimasto nella ciotola e completa con un filo d\'olio crudo e una fogliolina di basilico.' },
    ],
  },
  {
    id: 'demo-2',
    user_id: 'chef-nonna-rosa',
    author: {
      id: 'chef-nonna-rosa',
      username: 'nonna_rosa',
      full_name: 'Rosa Ferrari',
      avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Oltre 40 anni di sfoglia emiliana, funghi dell\'Appennino e ricette della tradizione.',
      is_private: false,
    },
    title: 'Tagliatelle Emiliane ai Funghi Porcini e Tartufo',
    category: 'Primi',
    prep_time: '30 min',
    servings: 4,
    calories: 1960,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { id: 'ing-7', name: 'Tagliatelle all\'uovo fresche trafilate', amount: '350g' },
      { id: 'ing-8', name: 'Funghi porcini freschi sodi (o surgelati di qualità)', amount: '450g' },
      { id: 'ing-9', name: 'Burro di malga fresco', amount: '40g' },
      { id: 'ing-10', name: 'Olio extravergine d\'oliva', amount: '2 cucchiai' },
      { id: 'ing-11', name: 'Spicchio d\'aglio in camicia', amount: '1 spicchio' },
      { id: 'ing-12', name: 'Prezzemolo fresco tritato finemente', amount: '2 cucchiai' },
      { id: 'ing-13', name: 'Parmigiano Reggiano DOP 24 mesi grattugiato', amount: '60g' },
      { id: 'ing-14', name: 'Pepe nero macinato al mulinello e sale', amount: 'q.b.' },
    ],
    steps: [
      { id: 'step-6', step: 1, instruction: 'Pulisci con cura i funghi porcini raschiando la terra dal gambo con un coltellino e passando un panno umido sulla cappella. Tagliali a fette spesse circa mezzo centimetro.' },
      { id: 'step-7', step: 2, instruction: 'In una padella ampia scalda l\'olio EVO e il burro con uno spicchio d\'aglio schiacciato. Unisci i porcini e falli rosolare a fiamma vivace per 5-6 minuti senza coprire, salando solo verso la fine.' },
      { id: 'step-8', step: 3, instruction: 'Porta a ebollizione abbondante acqua salata e cuoci le tagliatelle fresche per 2-3 minuti, scolandole molto al dente.' },
      { id: 'step-9', step: 4, instruction: 'Trasferisci la pasta direttamente nella padella con i funghi, aggiungendo un mestolino di acqua di cottura ricca di amido per creare un\'emulsione cremosa.' },
      { id: 'step-10', step: 5, instruction: 'Spegni il fuoco, unisci il Parmigiano Reggiano, il prezzemolo fresco tritato e manteca energicamente. Servi caldissimo con abbondante pepe nero.' },
    ],
  },
  {
    id: 'demo-3',
    user_id: 'chef-luigi-esposito',
    author: {
      id: 'chef-luigi-esposito',
      username: 'luigi_gourmet',
      full_name: 'Luigi Esposito',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Cucina di mare, sapori costieri e ricette di pesce equilibrate e raffinate.',
      is_private: false,
    },
    title: 'Filetto di Spigola alle Erbe Aromatiche e Patate Dorate',
    category: 'Secondi',
    prep_time: '35 min',
    servings: 2,
    calories: 780,
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { id: 'ing-15', name: 'Filetti di spigola (branzino) freschissimi', amount: '2 filetti (400g)' },
      { id: 'ing-16', name: 'Patate a pasta gialla novelle', amount: '350g' },
      { id: 'ing-17', name: 'Pomodorini ciliegino di Pachino', amount: '150g' },
      { id: 'ing-18', name: 'Olive taggiasche denocciolate sott\'olio', amount: '2 cucchiai' },
      { id: 'ing-19', name: 'Rosmarino e timo fresco', amount: 'qualche rametto' },
      { id: 'ing-20', name: 'Vino bianco secco fermo', amount: ' mezzo bicchiere' },
      { id: 'ing-21', name: 'Olio extravergine d\'oliva e sale fino', amount: 'q.b.' },
    ],
    steps: [
      { id: 'step-11', step: 1, instruction: 'Pela le patate e tagliale a rondelle sottili con una mandolina (circa 2 mm) per garantire una cottura uniforme.' },
      { id: 'step-12', step: 2, instruction: 'Disponi le rondelle di patate su una teglia foderata di carta forno, condisci con sale, pepe, aghi di rosmarino e olio EVO. Inforna a 200°C ventilato per 15 minuti finché iniziano a dorare.' },
      { id: 'step-13', step: 3, instruction: 'Estrai la teglia dal forno, adagia i filetti di spigola sopra il letto di patate con la pelle rivolta verso l\'alto.' },
      { id: 'step-14', step: 4, instruction: 'Aggiungi i pomodorini tagliati a metà, le olive taggiasche e le foglioline di timo. Sfuma con il vino bianco e spennella la pelle del pesce con un goccio d\'olio.' },
      { id: 'step-15', step: 5, instruction: 'Rimetti in forno per altri 12-14 minuti a 190°C. La pelle risulterà croccante e la polpa morbida e succosa. Servi subito con fette di limone fresco.' },
    ],
  },
  {
    id: 'demo-4',
    user_id: 'chef-chiara-valenti',
    author: {
      id: 'chef-chiara-valenti',
      username: 'chiara_cucina',
      full_name: 'Chiara Valenti',
      avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      bio: 'Pasticceria artigianale e dolci al cucchiaio. Il tiramisù è il mio cavallo di battaglia!',
      is_private: false,
    },
    title: 'Tiramisù Tradizionale al Mascarpone e Caffè Moka',
    category: 'Dolci',
    prep_time: '25 min (+ 4h riposo)',
    servings: 6,
    calories: 2880,
    created_at: new Date().toISOString(),
    image_url: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { id: 'ing-22', name: 'Savoiardi sardi o artigianali', amount: '300g' },
      { id: 'ing-23', name: 'Mascarpone fresco artigianale', amount: '500g' },
      { id: 'ing-24', name: 'Uova fresche biologiche (tuorli e albumi)', amount: '4 grandi' },
      { id: 'ing-25', name: 'Zucchero semolato finissimo', amount: '100g' },
      { id: 'ing-26', name: 'Caffè espresso da moka amaro (raffreddato)', amount: '300ml' },
      { id: 'ing-27', name: 'Cacao amaro in polvere di alta qualità', amount: 'q.b.' },
      { id: 'ing-28', name: 'Marsala secco o liquore all\'amaretto (facoltativo)', amount: '1 cucchiaio' },
    ],
    steps: [
      { id: 'step-16', step: 1, instruction: 'Prepara il caffè con la moka e lascialo raffreddare completamente in una ciotola larga, aromatizzandolo a piacere con un goccio di marsala.' },
      { id: 'step-17', step: 2, instruction: 'Separa i tuorli dagli albumi. Monta i tuorli con lo zucchero con le fruste elettriche fino a ottenere un composto chiaro, spumoso e vellutato.' },
      { id: 'step-18', step: 3, instruction: 'Aggiungi il mascarpone al composto di tuorli a cucchiaiate, continuando a mescolare delicatamente con una spatola dal basso verso l\'alto per non smontarlo.' },
      { id: 'step-19', step: 4, instruction: 'Monta gli albumi a neve ben ferma con un pizzico di sale e incorporali delicatamente alla crema di mascarpone.' },
      { id: 'step-20', step: 5, instruction: 'Inzuppa rapidamente i savoiardi nel caffè freddo (devono assorbire senza sfaldarsi) e stendine un primo strato fitto in una pirofila.' },
      { id: 'step-21', step: 6, instruction: 'Copri con metà della crema al mascarpone, fai un secondo strato di savoiardi e completa con la restante crema livellando con la spatola.' },
      { id: 'step-22', step: 7, instruction: 'Riponi in frigorifero per almeno 4 ore (meglio tutta la notte). Prima di servire, spolverizza generosamente la superficie con il cacao amaro setacciato.' },
    ],
  },
  {
    id: 'demo-5',
    user_id: 'chef-gennaro-romano',
    author: {
      id: 'chef-gennaro-romano',
      username: 'gennaro_chef',
      full_name: 'Gennaro Romano',
      avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
      bio: 'Cucina napoletana verace. Melanzane dorate e fritte a regola d\'arte.',
      is_private: false,
    },
    title: 'Parmigiana di Melanzane alla Napoletana',
    category: 'Antipasti',
    prep_time: '50 min',
    servings: 4,
    calories: 1640,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { id: 'ing-29', name: 'Melanzane scure o violette sode', amount: '3 grandi (1kg)' },
      { id: 'ing-30', name: 'Passata di pomodoro San Marzano DOP', amount: '700ml' },
      { id: 'ing-31', name: 'Mozzarella fiordilatte o provola affumicata', amount: '350g' },
      { id: 'ing-32', name: 'Parmigiano Reggiano grattugiato', amount: '80g' },
      { id: 'ing-33', name: 'Foglie di basilico fresco', amount: '10 foglie' },
      { id: 'ing-34', name: 'Olio per friggere o olio EVO per grigliare', amount: 'q.b.' },
    ],
    steps: [
      { id: 'step-23', step: 1, instruction: 'Lava le melanzane, tagliale a fette longitudinali di circa 5mm e spurgale per 30 minuti sotto sale per togliere l\'amaro.' },
      { id: 'step-24', step: 2, instruction: 'Sciacqua, asciuga bene le fette e friggile in olio ben caldo (oppure grigliale per una versione più leggera).' },
      { id: 'step-25', step: 3, instruction: 'Cuoci il sugo di pomodoro con un filo d\'olio, uno spicchio d\'aglio e abbondante basilico fresco per circa 15 minuti.' },
      { id: 'step-26', step: 4, instruction: 'Componi gli strati in una teglia: sul fondo un velo di sugo, poi melanzane, mozzarella a dadini ben asciutta, parmigiano e foglie di basilico.' },
      { id: 'step-27', step: 5, instruction: 'Inforna a 190°C per circa 25-30 minuti fino a creare una gratinatura dorata e irresistibile. Lascia intiepidire 15 minuti prima di servire.' },
    ],
  },
  {
    id: 'demo-6',
    user_id: 'chef-alessandro-conti',
    author: {
      id: 'chef-alessandro-conti',
      username: 'alessandro_conti',
      full_name: 'Alessandro Conti',
      avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
      bio: 'Chef milanese, risotti all\'onda e studio rigoroso delle mantecature.',
      is_private: false,
    },
    title: 'Risotto Carnaroli alla Milanese con Zafferano Puro',
    category: 'Primi',
    prep_time: '25 min',
    servings: 4,
    calories: 1720,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { id: 'ing-35', name: 'Riso Carnaroli autentico', amount: '320g' },
      { id: 'ing-36', name: 'Zafferano in stimmi o 2 bustine di polvere', amount: '1 dose' },
      { id: 'ing-37', name: 'Brodo di carne o vegetale bollente', amount: '1.2 litri' },
      { id: 'ing-38', name: 'Cipolla dorata tritata finissima', amount: '1 piccola' },
      { id: 'ing-39', name: 'Vino bianco secco', amount: '80ml' },
      { id: 'ing-40', name: 'Burro di latteria freddo da frigo', amount: '60g' },
      { id: 'ing-41', name: 'Grana Padano o Parmigiano DOP', amount: '70g' },
    ],
    steps: [
      { id: 'step-28', step: 1, instruction: 'Sciogli lo zafferano in mezza tazza di brodo caldo almeno 20 minuti prima di iniziare.' },
      { id: 'step-29', step: 2, instruction: 'Fai appassire la cipolla con 20g di burro a fuoco dolce fino a renderla trasparente, senza bruciarla.' },
      { id: 'step-30', step: 3, instruction: 'Aggiungi il riso e tostalo a secco per 2-3 minuti fino a quando i chicchi diventano traslucidi.' },
      { id: 'step-31', step: 4, instruction: 'Sfuma con il vino bianco, lascialo evaporare e inizia ad aggiungere il brodo bollente un mestolo alla volta, mescolando delicatamente.' },
      { id: 'step-32', step: 5, instruction: 'A metà cottura (dopo 10 minuti) versa l\'infuso di zafferano, che donerà il colore oro brillante e il suo profumo unico.' },
      { id: 'step-33', step: 6, instruction: 'Raggiunta la cottura al dente, togli dal fuoco e manteca all\'onda con il restante burro freddissimo a tocchetti e il formaggio grattugiato. Copri 2 minuti e servi all\'onda.' },
    ],
  },
];
